"""FastAPI application entry point."""

import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from sqlalchemy import inspect, text

from backend.config import engine, get_settings, setup_backend_logging
from data_generators.models import Base

# Import governance models so they register with Base.metadata
import backend.models.governance  # noqa: F401

logger = logging.getLogger(__name__)


def _apply_column_migrations(bind):
    """Add columns that create_all(checkfirst=True) can't add to existing tables."""
    inspector = inspect(bind)
    migrations = [
        ("conversational_interactions", "synthesis_data", "JSONB"),
    ]
    with bind.connect() as conn:
        for table, column, col_type in migrations:
            if table in inspector.get_table_names():
                existing = {c["name"] for c in inspector.get_columns(table)}
                if column not in existing:
                    conn.execute(text(f'ALTER TABLE {table} ADD COLUMN {column} {col_type}'))
                    conn.commit()
                    logger.info("Added column %s.%s (%s)", table, column, col_type)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup / shutdown lifecycle."""
    setup_backend_logging()
    logger.info("Creating governance tables (checkfirst=True)")
    Base.metadata.create_all(bind=engine, checkfirst=True)
    _apply_column_migrations(engine)
    logger.info("Backend startup complete")
    yield
    logger.info("Backend shutdown")


openapi_tags = [
    {
        "name": "query",
        "description": "Submit natural-language queries, check status, and follow up on prior queries.",
    },
    {
        "name": "agents",
        "description": "Invoke specialised AI agents directly and retrieve their findings.",
    },
    {
        "name": "alerts",
        "description": "List, acknowledge, and suppress alerts generated by agent findings.",
    },
    {
        "name": "dashboard",
        "description": "Pre-computed dashboard aggregations (pure SQL, no LLM).",
    },
    {
        "name": "feeds",
        "description": "Data freshness and system health checks.",
    },
    {
        "name": "websocket",
        "description": "WebSocket endpoints for real-time streaming of query processing phases.",
    },
]

app = FastAPI(
    title="Clinical Operations Intelligence System",
    version="0.1.0",
    description="LLM-first agentic intelligence for clinical trial operations. "
    "Provides autonomous agent-driven analysis of data quality, enrollment funnels, "
    "and operational metrics across clinical trial sites.",
    lifespan=lifespan,
    openapi_tags=openapi_tags,
    contact={
        "name": "Clinical Operations Intelligence Team",
        "url": "https://github.com/clinops-intel",
    },
    license_info={
        "name": "Proprietary",
    },
)

# CORS
settings = get_settings()
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Register routers
from backend.routers import query, agents, alerts, dashboard, feeds, ws  # noqa: E402

app.include_router(query.router, prefix="/api")
app.include_router(agents.router, prefix="/api")
app.include_router(alerts.router, prefix="/api")
app.include_router(dashboard.router, prefix="/api")
app.include_router(feeds.router, prefix="/api")
app.include_router(ws.router)


@app.get("/")
async def root():
    return {"service": "Clinical Operations Intelligence System", "version": "0.1.0"}
